// flow-typed signature: fb6a8ffddcc0a13903a4327482f97a2c
// flow-typed version: <<STUB>>/@caapim/themer_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@caapim/themer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@caapim/themer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@caapim/themer/lib/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/middleware/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/theme/index' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/Themer' {
  declare module.exports: any;
}

declare module '@caapim/themer/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@caapim/themer/lib/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/index'>;
}
declare module '@caapim/themer/lib/middleware/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/middleware/index'>;
}
declare module '@caapim/themer/lib/theme/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/theme/index'>;
}
declare module '@caapim/themer/lib/Themer.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/Themer'>;
}
declare module '@caapim/themer/lib/utils/index.js' {
  declare module.exports: $Exports<'@caapim/themer/lib/utils/index'>;
}
